### PR TITLE
Add .mpdl file for 3.0 version

### PR DESCRIPTION
**Pull request by cazfi**
In case you want support installing with modpack installer.

Didn't touch README.md. You may also want to adjust the name of the file (but suffix needs to be '.mpdl')

Once this is in your repo, URL to use in modpack installer will be:
https://raw.githubusercontent.com/dftec-es/civ2civ3_earth/master/3.0/civ2civ3_earth-2023_alpha-3.0.mpdl

One you have a stable version, I'd like to have it also in installer's list of modpacks to suggest.

### CODE REVIEW

**Comment by dftec-es** [comment]
Great, thank you. I'll add it.

When I get a stable version, I was planing to send you the pack and ask to host it on modpack.freeciv.org like I used to do. But I guess this new method would not require that. I'll add the .mpdl to v2.6 too, and I'll let you know when both versions are ready to be released.

One question from someone new to git: if someone uses that URL to install with modpack installer, I suppose it will install the latest commit of the master. If I want only certain commits that I have played and tested properly to appear in the modpack installer, what would you suggest:

1) to create a different branch for modpack installer releases, and to add the .mpdl there
2) to stop updating the master with alphas/betas, and to commit only final versions ready to be played
3) something else

**Comment by cazfi** [comment]
In 2.6 it still had ".modpack" suffix. Be also sure to have format otherwise compatible.

As the baseURL in the .mpdl I provided is "./", everything depends on how one access IT. I believe that you can use also tag name, or even commit hash, in that URL (path component where my example had "master" branch).

**Comment by dftec-es** [comment]
Ok, I checked the README.modpack_installer for 2.6, I think the format will be compatible.

**Comment by dftec-es** [comment]
It is working now. I tested both 2.6 and 3.0, and I updated the readme.
It is a nice way to install the modpack, thank you very much for pointing it here.

> As the baseURL in the .mpdl I provided is "./"

I had to change the baseURL to "." in order to get it working. It was easy to find the problem because it is properly documented in README.modpack_installer.

**Pull request merged**
